HospitalManagementSystem/Areas/Admin/Controllers/DoctorController.cs
using HospitalManagementSystem.Data.Repository.IRepository;
using HospitalManagementSystem.Models.ViewModels;
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using HospitalManagementSystem.Utility;

namespace HospitalManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
        
    public class DoctorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public DoctorController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var doctorList = _unitOfWork.Doctor.GetAll(includeProperties: "Department");
            return Json(new { data = doctorList });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var doctor = _unitOfWork.Doctor.Get(id);
            if (doctor == null)
                return Json(new { success = false, message = "Something went wrong while deleting data!!!" });
            var webRootPath = _webHostEnvironment.WebRootPath;
            var imagePath = Path.Combine(webRootPath, doctor.ImageUrl.Trim('\\'));
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }
            _unitOfWork.Doctor.Remove(doctor);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Data deleted successfully!!!" });

        }


        #endregion

        public IActionResult Upsert(int? id)
        {
            DoctorVM doctorVM = new DoctorVM()
            {
                DepartmentList = _unitOfWork.Department.GetAll().Select(cl => new SelectListItem()
                {
                    Text = cl.Name,
                    Value = cl.Id.ToString(),
                }),
                Doctor = new Doctor()
            };
            if (id == null) return View(doctorVM);  //Create
            //Edit
            doctorVM.Doctor = _unitOfWork.Doctor.Get(id.GetValueOrDefault());
            return View(doctorVM);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Upsert(DoctorVM doctorVM)
        {
            if (ModelState.IsValid)
            {
                var webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0)
                {
                    var filename = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(files[0].FileName);
                    var uploads = Path.Combine(webRootPath, @"images\products");
                    if (doctorVM.Doctor.Id != 0)
                    {
                        var imageExists = _unitOfWork.Hospital.Get(doctorVM.Doctor.Id).ImageUrl;
                        doctorVM.Doctor.ImageUrl = imageExists;
                    }
                    if (doctorVM.Doctor.ImageUrl != null)
                    {
                        var imagePath = Path.Combine(webRootPath, doctorVM.Doctor.ImageUrl.Trim('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(uploads, filename + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    doctorVM.Doctor.ImageUrl = @"\images\products\" + filename + extension;
                }
                else
                {
                    if (doctorVM.Doctor.Id != 0)
                    {
                        var imageExists = _unitOfWork.Hospital.Get(doctorVM.Doctor.Id).ImageUrl;
                        doctorVM.Doctor.ImageUrl = imageExists;
                    }

                }
                if (doctorVM.Doctor.Id == 0)
                {
                    _unitOfWork.Doctor.Add(doctorVM.Doctor);
                }
                else
                {
                    _unitOfWork.Doctor.Update(doctorVM.Doctor);
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            else
            {
                doctorVM = new DoctorVM()
                {
                    DepartmentList = _unitOfWork.Department.GetAll().Select(cl => new SelectListItem()
                    {
                        Text = cl.Name,
                        Value = cl.Id.ToString(),
                    }),
                    Doctor = new Doctor()

                };
                if (doctorVM.Doctor.Id != 0)
                {
                    doctorVM.Doctor = _unitOfWork.Doctor.Get(doctorVM.Doctor.Id);
                }
                return View(doctorVM);
            }
        }


    }
}

HospitalManagementSystem/Areas/Admin/Controllers/HospitalController.cs
using HospitalManagementSystem.Data.Repository.IRepository;
using HospitalManagementSystem.Models;
using HospitalManagementSystem.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HospitalManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HospitalController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public HospitalController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var hospitalList = _unitOfWork.Hospital.GetAll(includeProperties: "HospitalType");
            return Json(new { data = hospitalList });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var hospital = _unitOfWork.Hospital.Get(id);
            if (hospital == null)
                return Json(new { success = false, message = "Something went wrong while deleting data!!!" });
            var webRootPath = _webHostEnvironment.WebRootPath;
            var imagePath = Path.Combine(webRootPath, hospital.ImageUrl.Trim('\\'));
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }
            _unitOfWork.Hospital.Remove(hospital);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Data deleted successfully!!!" });

        }
        #endregion

        public IActionResult Upsert(int? id)
        {
            HospitalVM hospitalVM = new HospitalVM()
            {
                HospitalTypeList = _unitOfWork.HospitalType.GetAll().Select(cl => new SelectListItem()
                {
                    Text = cl.Type,
                    Value = cl.Id.ToString(),
                }),
                Hospital = new Hospital()
            };
            if (id == null) return View(hospitalVM);  //Create
            //Edit
            hospitalVM.Hospital = _unitOfWork.Hospital.Get(id.GetValueOrDefault());
            return View(hospitalVM);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Upsert(HospitalVM hospitalVM)
        {
            if (ModelState.IsValid)
            {
                var webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0)
                {
                    var filename = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(files[0].FileName);
                    var uploads = Path.Combine(webRootPath, @"images\products");
                    if (hospitalVM.Hospital.Id != 0)
                    {
                        var imageExists = _unitOfWork.Hospital.Get(hospitalVM.Hospital.Id).ImageUrl;
                        hospitalVM.Hospital.ImageUrl = imageExists;
                    }
                    if (hospitalVM.Hospital.ImageUrl != null)
                    {
                        var imagePath = Path.Combine(webRootPath, hospitalVM.Hospital.ImageUrl.Trim('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(uploads, filename + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    hospitalVM.Hospital.ImageUrl = @"\images\products\" + filename + extension;
                }
                else
                {
                    if (hospitalVM.Hospital.Id != 0)
                    {
                        var imageExists = _unitOfWork.Hospital.Get(hospitalVM.Hospital.Id).ImageUrl;
                        hospitalVM.Hospital.ImageUrl = imageExists;
                    }

                }
                if (hospitalVM.Hospital.Id == 0)
                {
                    _unitOfWork.Hospital.Add(hospitalVM.Hospital);
                }
                else
                {
                    _unitOfWork.Hospital.Update(hospitalVM.Hospital);
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            else
            {
                hospitalVM = new HospitalVM()
                {
                    HospitalTypeList = _unitOfWork.HospitalType.GetAll().Select(cl => new SelectListItem()
                    {
                        Text = cl.Type,
                        Value = cl.Id.ToString(),
                    }),
                    Hospital = new Hospital()

                };
                if (hospitalVM.Hospital.Id != 0)
                {
                    hospitalVM.Hospital = _unitOfWork.Hospital.Get(hospitalVM.Hospital.Id);
                }
                return View(hospitalVM);
            }
        }
    }
}

HospitalManagementSystem/Areas/Admin/Controllers/HospitalTypesController.cs
using HospitalManagementSystem.Data;
using HospitalManagementSystem.Data.Repository.IRepository;
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HospitalTypesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public HospitalTypesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        #region APIs
        [AllowAnonymous]
        [HttpGet]
        public IActionResult GetAll()
        {
            var hospitalType=_unitOfWork.HospitalType.GetAll();
            return Json(new { data = hospitalType });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var type = _unitOfWork.HospitalType.Get(id);
            if (type == null)
                return Json(new { success = false, message = "Something Went Wrong while Delete Data!!!" });
            _unitOfWork.HospitalType.Remove(type);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Data Deleted Successfully!!!" });
        }

        #endregion

        public IActionResult Upsert(int? id)
        {
            HospitalType hospitalType = new HospitalType();
            if (id == null) return View(hospitalType);
            hospitalType = _unitOfWork.HospitalType.Get(id.GetValueOrDefault());
            if (hospitalType == null) return NotFound();
            return View(hospitalType);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Upsert(HospitalType hospitalType)
        {
            if (hospitalType == null) return NotFound();
            if (!ModelState.IsValid) return View(hospitalType);
            if (hospitalType.Id == 0)
                _unitOfWork.HospitalType.Add(hospitalType);
            else
                _unitOfWork.HospitalType.Update(hospitalType);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }



    }
}

HospitalManagementSystem/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control">Save</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">
            Back To List
        </a>
    </div>
</div>

HospitalManagementSystem/Views/Shared/_EditAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">
            Back To List
        </a>
    </div>
</div>

HospitalManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalManagementSystem.styles.css" asp-append-version="true" />

    @*CSS REF*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

</head>
@* <body style="background-image:linear-gradient(rgba(255,255,255,.5),rgba(255,255,255,.5)),url(../../images/encounters.jpg); background-size: cover; 
background-position: top;"> *@


        <body style="background-image: linear-gradient(rgba(255, 255, 255, 0.5), rgba(0, 255, 255, 0.5)),url(../../images/encounters.jpg);
                background-size: cover; background-position: top; content-visibility: visible;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @*  <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> *@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item col-1">
                            <img width="70%" height="100%" src="~/images/hospitals.jpg" />
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hospitals List</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="Index" asp-controller="HospitalTypes" asp-area="Admin">Types of Hospitals</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Hospital" asp-area="Admin">List of Hospitals</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hospital Management</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Department" asp-area="Admin">Departments or Wards</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Doctor" asp-area="Admin">Doctors</a>

                            </div>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
                </div>
      
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <br/>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    

    <div class="row">
        <marquee behavior="scroll" direction="left" class="text-center fw-bold"
                 style="color:black; font-family:Georgia Extrabold,sans-serif;font-size:2em;">
            Welcome to Healthcare-Information-Management-System
        </marquee>
    </div>

    <footer class="border-top footer text-muted ">
        <div class="container text-white">
            &copy; Copyright © 2024 - HospitalManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a>
         <br/> Powered By: Amritjyot Kaur
            <br/>
           @*  <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a> *@
        </div>
    </footer>

    @* <footer class="border-top footer text-muted bg-primary p-5">
        <div class="container text-white">
            &copy; 2024 - HospitalManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*JS REF*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>